### PR TITLE
Sprint2 TOML

### PR DESCRIPTION
**Pull request by Vitaliy-Kost**
# Sprint 2 
## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by stratiiv** [comment]
please: 
* update your folder name as appropriate
* fix your github template

**Comment by stratiiv** [comment]
Please leave the instruction how to run
image

**Comment by Vitaliy-Kost** [comment]
щось не можу зрозуміти  чому кодеки матюкаються, видали китайські символи,
або взагалі видали все з example файлу, залиш тільки пару lines, чи пройде

**Comment by Vitaliy-Kost** [comment]
check plz

**Review by stratiiv — APPROVED** [review]

**Review by magyrka — APPROVED** [review]

**Review by elzvoe — APPROVED** [review]

**Pull request merged**
