### PR TITLE
implement task json

### PR DESCRIPTION
**Pull request by magyrka**
# Description
Added new folder with task-json with script, .json file for test and usage instructions

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by stratiiv** [comment]
Your scripts returns only one value 
You need to handle case when there are multiple passwords in file

**Comment by magyrka** [comment]
fixed issue with passwords. added func to handle any json tree structure

**Review by elzvoe — COMMENTED** [review]
print each password in separate lines

**Comment by magyrka** [comment]
> print each password in separate lines

done

**Review by stratiiv — APPROVED** [review]

**Review by rohirniak — APPROVED** [review]

**Pull request merged**
